logging:
  file:
    path: ./logs
  level:
    com:
      twcch: DEBUG
    root: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/mysql_mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8